"""empty message

Revision ID: dba1787c01d3
Revises: 09c688db4f59
Create Date: 2022-07-17 15:16:03.652882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dba1787c01d3'
down_revision = '09c688db4f59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('game', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'games', ['game'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'game')
    # ### end Alembic commands ###
